"""Render MediaMTX's config from the stored state.

MediaMTX watches its own config file and reloads on change, which is the
reason it is worth generating rather than hand-editing: turning the
stream on in the UI can take effect without anyone restarting a
container. If that reload is ever missed, ``docker compose restart
rtsp-server`` is the fallback and costs the Connector one reconnect.

Two users, deliberately. The read user is the one pasted into Verkada,
and it can only read; a credential handed to a third-party appliance
should not be able to publish over the stream that appliance is
watching. The publish user never leaves this compose network.

A malformed config does not fail visibly at this end. MediaMTX refuses
to start, the container exits, its DNS name stops resolving, and what
reaches the operator is the encoder reporting "Failed to resolve
hostname rtsp-server" -- a networking error for what is really a syntax
error, several layers away from the cause. ``validate()`` exists so that
a config that would not parse is refused here instead.
"""

from __future__ import annotations

import logging
from typing import Any

from app.rtsp import settings


logger = logging.getLogger(__name__)


DENY_ALL = """# Placeholder written by vFusion. Replaced with a real config, including
# credentials, the moment the virtual camera is turned on.
#
# It denies everything on purpose. The container has to be up before
# vFusion can write credentials into it, and an RTSP server briefly wide
# open on the LAN while that happens is not a reasonable default.
logLevel: info
logDestinations: [stdout]
rtsp: yes
rtspTransports: [tcp]
rtspAddress: :8554
rtmp: no
hls: no
webrtc: no
srt: no
moq: no
api: yes
apiAddress: :9997
authMethod: internal
authInternalUsers: []
paths: {}
"""


def render(state: dict[str, Any]) -> str:
    stream = state.get("stream") or settings.DEFAULT_STREAM
    sub = settings.sub_stream(state)
    read_user = state.get("read_username") or "verkada"
    read_pass = state.get("read_password") or ""
    pub_user = state.get("publish_username") or "vfusion"
    pub_pass = state.get("publish_password") or ""

    return f"""# Generated by vFusion. Edits here are overwritten whenever the
# virtual camera settings change -- change them in the UI instead.
logLevel: info
logDestinations: [stdout]

# Only RTSP. The Command Connector speaks it, and every other protocol
# this server can offer is another way in that nothing here needs.
rtsp: yes
# TCP only, and not as a preference -- only the TCP port is published to
# the LAN. Advertising UDP would let a client negotiate a transport whose
# RTP ports never leave this container, which presents as a stream that
# connects and then shows nothing.
rtspTransports: [tcp]
rtspAddress: :{settings.PORT}
rtmp: no
hls: no
webrtc: no
srt: no
# Off explicitly: MediaMTX starts MoQ by default and generates itself a
# certificate for it on first boot. Nothing here speaks it.
moq: no

# The HTTP API is how vFusion answers "is the Connector actually pulling
# this?" -- it reports readers per path, which is the difference between
# publishing into the void and being watched.
api: yes
apiAddress: :9997

authMethod: internal
authInternalUsers:
  - user: {pub_user}
    pass: {pub_pass}
    ips: []
    permissions:
      - action: publish
        path: {stream}
      - action: publish
        path: {sub}
  - user: {read_user}
    pass: {read_pass}
    ips: []
    permissions:
      - action: read
        path: {stream}
      - action: read
        path: {sub}
  # No anonymous entry. MediaMTX ships one by default that grants
  # everything to everyone; leaving it out is the point of this file.

paths:
  # Main and sub are published by the same encoder process, so they are
  # always both present or both absent.
  {stream}:
    source: publisher
  {sub}:
    source: publisher
"""


def validate(text: str) -> str | None:
    """Why MediaMTX would reject this config, or None if it looks sound.

    Cheap insurance. The cost of not checking is not a bad file on disk:
    it is a container that exits, a hostname that stops resolving, and an
    error about DNS at the far end of the system.
    """
    try:
        import yaml
    except ImportError:
        return None
    try:
        parsed = yaml.safe_load(text)
    except yaml.YAMLError as e:
        return f"not valid YAML: {e}"
    if not isinstance(parsed, dict):
        return "config is not a mapping"
    for key in ("rtsp", "rtspAddress", "authInternalUsers", "paths"):
        if key not in parsed:
            return f"config is missing {key}"
    return None


def ensure(state: dict[str, Any]) -> bool:
    """Make sure a config exists at boot, whether or not the camera is on.

    The sidecar mounts this file and will not start without it, so a
    fresh checkout has to produce one before MediaMTX's first restart
    attempt gives up. Off means deny-all rather than absent.

    A config that fails to validate is replaced with the deny-all one:
    a server that starts and refuses connections can be diagnosed from
    the UI, and a server that will not start cannot.
    """
    if state.get("enabled") and write(state):
        return True
    if settings.CONFIG_PATH.exists() and not state.get("enabled"):
        return True
    return _write_text(DENY_ALL)


def write(state: dict[str, Any]) -> bool:
    """Write the config out. False if it would not parse, or cannot be saved."""
    text = render(state)
    problem = validate(text)
    if problem:
        logger.error("refusing to write mediamtx config: %s", problem)
        return False
    return _write_text(text)


def _write_text(text: str) -> bool:
    """Write only if the contents actually changed.

    MediaMTX does not reload its config in place -- it shuts down and
    starts again, which drops every session including the one publishing
    the stream. Rewriting an identical file therefore costs the Command
    Connector a reconnect for nothing, and vFusion rewrites this on every
    boot and every settings save. Comparing first turns those into no-ops.
    """
    try:
        if settings.CONFIG_PATH.exists() and settings.CONFIG_PATH.read_text() == text:
            return True
    except OSError:
        pass  # unreadable is a reason to write, not to give up
    try:
        settings.CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
        tmp = settings.CONFIG_PATH.with_suffix(".tmp")
        tmp.write_text(text)
        tmp.replace(settings.CONFIG_PATH)
        return True
    except OSError as e:
        logger.warning("could not write mediamtx config: %s", e)
        return False


async def readers(stream: str) -> int | None:
    """How many clients are pulling the path. None if the API is unreachable.

    None and 0 are different answers and the UI says so: one means the
    server is not talking to us, the other means nobody is watching.
    """
    import httpx

    url = f"http://{settings.INTERNAL_HOST}:9997/v3/paths/get/{stream}"
    try:
        async with httpx.AsyncClient(timeout=2.0) as client:
            resp = await client.get(url)
        if resp.status_code != 200:
            return None
        data = resp.json()
    except Exception:
        return None
    value = data.get("readers")
    if isinstance(value, list):
        return len(value)
    return None
