"""Render MediaMTX's config from the stored state.

MediaMTX watches its own config file and reloads on change, which is the
reason it is worth generating rather than hand-editing: turning the
stream on in the UI can take effect without anyone restarting a
container. If that reload is ever missed, ``docker compose restart
rtsp-server`` is the fallback and costs the Connector one reconnect.

Two users, deliberately. The read user is the one pasted into Verkada,
and it can only read; a credential handed to a third-party appliance
should not be able to publish over the stream that appliance is
watching. The publish user never leaves this compose network.

A malformed config does not fail visibly at this end. MediaMTX refuses
to start, the container exits, its DNS name stops resolving, and what
reaches the operator is the encoder reporting "Failed to resolve
hostname rtsp-server" -- a networking error for what is really a syntax
error, several layers away from the cause. ``validate()`` exists so that
a config that would not parse is refused here instead.
"""

from __future__ import annotations

import logging
from typing import Any

from app.rtsp import settings


logger = logging.getLogger(__name__)


DENY_ALL = """# Placeholder written by vFusion. Replaced with a real config, including
# credentials, the moment the virtual camera is turned on.
#
# It denies everything on purpose. The container has to be up before
# vFusion can write credentials into it, and an RTSP server briefly wide
# open on the LAN while that happens is not a reasonable default.
logLevel: info
logDestinations: [stdout]
rtsp: yes
rtspTransports: [tcp]
rtspAddress: :8554
rtmp: no
hls: no
webrtc: no
srt: no
moq: no
api: yes
apiAddress: :9997
authMethod: internal
authInternalUsers: []
paths: {}
"""


def render(state: dict[str, Any]) -> str:
    stream = state.get("stream") or settings.DEFAULT_STREAM
    sub = settings.sub_stream(state)
    # Only ONVIF can describe a second profile, so in RTSP mode the path
    # would sit there permanently unpublished — which MediaMTX reports as
    # a path with no source, and which reads like something broken.
    onvif = settings.is_onvif(state)
    sub_publish = f"\n      - action: publish\n        path: {sub}" if onvif else ""
    sub_read = f"\n      - action: read\n        path: {sub}" if onvif else ""
    sub_path = f"\n  {sub}:\n    source: publisher" if onvif else ""
    read_user = state.get("read_username") or "verkada"
    read_pass = state.get("read_password") or ""
    pub_user = state.get("publish_username") or "vfusion"
    pub_pass = state.get("publish_password") or ""
    api_user = state.get("api_username") or "vfusionapi"
    api_pass = state.get("api_password") or ""

    return f"""# Generated by vFusion. Edits here are overwritten whenever the
# virtual camera settings change -- change them in the UI instead.
logLevel: info
logDestinations: [stdout]

# Only RTSP. The Command Connector speaks it, and every other protocol
# this server can offer is another way in that nothing here needs.
rtsp: yes
# TCP only, and not as a preference -- only the TCP port is published to
# the LAN. Advertising UDP would let a client negotiate a transport whose
# RTP ports never leave this container, which presents as a stream that
# connects and then shows nothing.
rtspTransports: [tcp]
rtspAddress: :{settings.PORT}
rtmp: no
hls: no
webrtc: no
srt: no
# Off explicitly: MediaMTX starts MoQ by default and generates itself a
# certificate for it on first boot. Nothing here speaks it.
moq: no

# On, for the viewer count. Reachable only on the compose network --
# nothing publishes 9997 to the LAN -- so it answers vFusion and nothing
# else.
api: yes
apiAddress: :9997

authMethod: internal
authInternalUsers:
  - user: {pub_user}
    pass: {pub_pass}
    ips: []
    permissions:
      - action: publish
        path: {stream}{sub_publish}
  - user: {read_user}
    pass: {read_pass}
    ips: []
    permissions:
      - action: read
        path: {stream}{sub_read}
  # vFusion asking the server about itself. "api" is a permission like
  # publish and read, so dropping the default anonymous user revoked it
  # too — and every status call came back 401 while the page reported an
  # unknown viewer count and could not tell whether a path was missing.
  # The API port is not published to the LAN, so this is reachable only
  # from the compose network; the password is belt and braces.
  - user: {api_user}
    pass: {api_pass}
    ips: []
    permissions:
      - action: api
  # No anonymous entry. MediaMTX ships one by default that grants
  # everything to everyone; leaving it out is the point of this file.

paths:
  # The sub path exists only in ONVIF mode, because only ONVIF can
  # describe a second profile. Switching to plain RTSP removes it — and
  # a Command Connector added over ONVIF keeps asking for it, is refused
  # every second, and goes offline. If you are reading this file because
  # a camera dropped, that is the first thing to check.
  {stream}:
    source: publisher{sub_path}
"""


def validate(text: str) -> str | None:
    """Why MediaMTX would reject this config, or None if it looks sound.

    Cheap insurance. The cost of not checking is not a bad file on disk:
    it is a container that exits, a hostname that stops resolving, and an
    error about DNS at the far end of the system.
    """
    try:
        import yaml
    except ImportError:
        return None
    try:
        parsed = yaml.safe_load(text)
    except yaml.YAMLError as e:
        return f"not valid YAML: {e}"
    if not isinstance(parsed, dict):
        return "config is not a mapping"
    for key in ("rtsp", "rtspAddress", "authInternalUsers", "paths"):
        if key not in parsed:
            return f"config is missing {key}"
    return None


def ensure(state: dict[str, Any]) -> bool:
    """Make sure a config exists at boot, whether or not the camera is on.

    The sidecar mounts this file and will not start without it, so a
    fresh checkout has to produce one before MediaMTX's first restart
    attempt gives up. Off means deny-all rather than absent.

    A config that fails to validate is replaced with the deny-all one:
    a server that starts and refuses connections can be diagnosed from
    the UI, and a server that will not start cannot.
    """
    if state.get("enabled") and write(state):
        return True
    if settings.CONFIG_PATH.exists() and not state.get("enabled"):
        return True
    return _write_text(DENY_ALL)


def write(state: dict[str, Any]) -> bool:
    """Write the config out. False if it would not parse, or cannot be saved."""
    text = render(state)
    problem = validate(text)
    if problem:
        logger.error("refusing to write mediamtx config: %s", problem)
        return False
    return _write_text(text)


def _api_auth() -> tuple[str, str]:
    """Credentials for MediaMTX's own API, from the same state that
    generated the config granting them."""
    state = settings.get()
    return (
        state.get("api_username") or "vfusionapi",
        state.get("api_password") or "",
    )


async def viewers(streams: list[str]) -> tuple[int | None, str]:
    """(clients reading these paths, why not).

    Asks for the whole path list and matches by name rather than fetching
    each path by id. get/{name} 404s for a path that exists in the config
    but has never been published to, which is indistinguishable from a
    server that is not answering -- and that is exactly the state
    everything was in the last time this was wired up.

    None is "we do not know" and carries the reason; 0 is "asked, nobody
    is watching". Reporting both as None is what made this useless
    before.
    """
    import httpx

    url = f"http://{settings.INTERNAL_HOST}:9997/v3/paths/list"
    try:
        async with httpx.AsyncClient(timeout=2.0) as client:
            resp = await client.get(url, auth=_api_auth())
    except Exception as e:
        return None, f"cannot reach the RTSP server's API: {e}"
    if resp.status_code != 200:
        return None, f"the RTSP server's API answered {resp.status_code}"
    try:
        items = (resp.json() or {}).get("items")
    except ValueError:
        return None, "the RTSP server's API returned something that is not JSON"
    if not isinstance(items, list):
        return None, "no path list in the API response"

    wanted = set(streams)
    total = 0
    seen = False
    for item in items:
        if not isinstance(item, dict) or item.get("name") not in wanted:
            continue
        seen = True
        readers = item.get("readers")
        if isinstance(readers, list):
            total += len(readers)
    if not seen:
        # The server is answering, it just has no record of these paths --
        # nothing has published to them yet.
        return 0, ""
    return total, ""


def _write_text(text: str) -> bool:
    """Write only if the contents actually changed.

    MediaMTX does not reload its config in place -- it shuts down and
    starts again, which drops every session including the one publishing
    the stream. Rewriting an identical file therefore costs the Command
    Connector a reconnect for nothing, and vFusion rewrites this on every
    boot and every settings save. Comparing first turns those into no-ops.
    """
    try:
        if settings.CONFIG_PATH.exists() and settings.CONFIG_PATH.read_text() == text:
            return True
    except OSError:
        pass  # unreadable is a reason to write, not to give up
    try:
        settings.CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
        tmp = settings.CONFIG_PATH.with_suffix(".tmp")
        tmp.write_text(text)
        tmp.replace(settings.CONFIG_PATH)
        return True
    except OSError as e:
        logger.warning("could not write mediamtx config: %s", e)
        return False


async def path_health(expected: list[str]) -> dict[str, object]:
    """Which of the paths we expect the server actually has.

    The encoder being alive says nothing about whether the server is
    serving what a client asks for. A Command Connector added over
    ONVIF pulls two paths, and if the config lost the sub path it
    reconnects every second and is refused every second — while
    vFusion, watching only its own ffmpeg process, reports that
    everything is fine. That is precisely the failure this exists to
    make visible.

    ``ready`` is MediaMTX's own word for a path with a live publisher;
    a path that is configured but unpublished is present and not ready,
    which is a different problem with a different fix.
    """
    import httpx

    url = f"http://{settings.INTERNAL_HOST}:9997/v3/paths/list"
    try:
        async with httpx.AsyncClient(timeout=2.0) as client:
            resp = await client.get(url, auth=_api_auth())
    except Exception as e:  # noqa: BLE001
        return {"known": False, "why": f"cannot reach the RTSP server's API: {e}"}
    if resp.status_code != 200:
        return {"known": False, "why": f"the RTSP server's API answered {resp.status_code}"}
    try:
        items = (resp.json() or {}).get("items") or []
    except ValueError:
        return {"known": False, "why": "the RTSP server's API returned something that is not JSON"}

    present: dict[str, bool] = {}
    for item in items:
        if isinstance(item, dict) and item.get("name"):
            present[str(item["name"])] = bool(item.get("ready"))

    missing = [p for p in expected if p not in present]
    not_ready = [p for p in expected if p in present and not present[p]]
    return {
        "known": True,
        "expected": expected,
        "present": sorted(present),
        "missing": missing,
        "not_ready": not_ready,
        "ok": not missing and not not_ready,
    }


async def readers(expected: list[str]) -> dict[str, object]:
    """Who is pulling the stream, not just how many.

    The count answers "is anything watching"; the next question is
    always "is that the Connector or something else", and only the
    session list carries the address. Publishers are filtered out — the
    encoder is always one of them, and reporting vFusion as a viewer of
    its own stream is noise dressed as information.
    """
    import httpx

    url = f"http://{settings.INTERNAL_HOST}:9997/v3/rtspsessions/list"
    try:
        async with httpx.AsyncClient(timeout=2.0) as client:
            resp = await client.get(url, auth=_api_auth())
    except Exception as e:  # noqa: BLE001
        return {"known": False, "why": f"cannot reach the RTSP server's API: {e}"}
    if resp.status_code != 200:
        return {"known": False, "why": f"the RTSP server's API answered {resp.status_code}"}
    try:
        items = (resp.json() or {}).get("items") or []
    except ValueError:
        return {"known": False, "why": "the RTSP server's API returned something that is not JSON"}

    wanted = set(expected)
    out: list[dict[str, object]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        if item.get("state") != "read":
            continue
        path = str(item.get("path") or "")
        if wanted and path not in wanted:
            continue
        out.append(
            {
                "id": item.get("id"),
                "address": item.get("remoteAddr"),
                "path": path,
                "since": item.get("created"),
                "transport": item.get("transport"),
                "bytes_sent": item.get("bytesSent"),
            }
        )
    return {"known": True, "readers": out}
