"""Render MediaMTX's config from the stored state.

MediaMTX watches its own config file and reloads on change, which is the
reason it is worth generating rather than hand-editing: turning the
stream on in the UI can take effect without anyone restarting a
container. If that reload ever fails to happen, ``docker compose restart
rtsp-server`` is the fallback and costs the Connector one reconnect.

Two users, deliberately. The read user is the one pasted into Verkada,
and it can only read; a credential handed to a third-party appliance
should not be able to publish over the stream that appliance is
watching. The publish user never leaves this compose network.
"""

from __future__ import annotations

import logging
from typing import Any

from app.rtsp import settings


logger = logging.getLogger(__name__)


def render(state: dict[str, Any]) -> str:
    stream = state.get("stream") or settings.DEFAULT_STREAM
    read_user = state.get("read_username") or "verkada"
    read_pass = state.get("read_password") or ""
    pub_user = state.get("publish_username") or "vfusion"
    pub_pass = state.get("publish_password") or ""

    return f"""# Generated by vFusion. Edits here are overwritten whenever the
# virtual camera settings change -- change them in the UI instead.
logLevel: info
logDestinations: [stdout]

# Only RTSP. The Command Connector speaks it, and every other protocol
# this server can offer is another way in that nothing here needs.
rtsp: yes
# TCP only, and not as a preference -- only the TCP port is published to
# the LAN. Advertising UDP would let a client negotiate a transport whose
# RTP ports never left this container, which fails as a stream that
# connects and then shows nothing.
rtspTransports: [tcp]
rtspAddress: :{settings.PORT}
rtmp: no
hls: no
webrtc: no
srt: no
# Off explicitly: MediaMTX starts MoQ by default and generates a
# certificate for it on first boot. Nothing here speaks it.
moq: no
A
($s =~ s/\Q$o\E/$n/) or die "render";

$o = <<'A';
rtsp: yes
rtspAddress: :8554
rtmp: no
hls: no
webrtc: no
srt: no
A
$n = <<'B';
rtsp: yes
rtspTransports: [tcp]
rtspAddress: :8554
rtmp: no
hls: no
webrtc: no
srt: no
moq: no

# The HTTP API is how vFusion answers "is the Connector actually pulling
# this?" -- it reports readers per path, which is the difference between
# publishing into the void and being watched.
api: yes
apiAddress: :9997

authMethod: internal
authInternalUsers:
  - user: {pub_user}
    pass: {pub_pass}
    ips: []
    permissions:
      - action: publish
        path: {stream}
  - user: {read_user}
    pass: {read_pass}
    ips: []
    permissions:
      - action: read
        path: {stream}
  # No anonymous entry. MediaMTX ships one by default that grants
  # everything to everyone; leaving it out is the point of this file.

paths:
  {stream}:
    source: publisher
"""


DENY_ALL = """# Placeholder written by vFusion. Replaced with a real config, including
# credentials, the moment the virtual camera is turned on.
#
# It denies everything on purpose. The container has to be up before
# vFusion can write credentials into it, and an RTSP server briefly wide
# open on the LAN while that happens is not a reasonable default.
logLevel: info
logDestinations: [stdout]
rtsp: yes
rtspAddress: :8554
rtmp: no
hls: no
webrtc: no
srt: no
api: yes
apiAddress: :9997
authMethod: internal
authInternalUsers: []
paths: {}
"""


def ensure(state: dict[str, Any]) -> bool:
    """Make sure a config exists at boot, whether or not the camera is on.

    The sidecar mounts this file and will not start without it, so a
    fresh checkout has to produce one before MediaMTX's first restart
    attempt gives up. Off means deny-all rather than absent.
    """
    if state.get("enabled"):
        return write(state)
    try:
        settings.CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
        if settings.CONFIG_PATH.exists():
            return True
        tmp = settings.CONFIG_PATH.with_suffix(".tmp")
        tmp.write_text(DENY_ALL)
        tmp.replace(settings.CONFIG_PATH)
        return True
    except OSError as e:
        logger.warning("could not write placeholder mediamtx config: %s", e)
        return False


def write(state: dict[str, Any]) -> bool:
    """Write the config out. False if the path is not mounted."""
    try:
        settings.CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
        tmp = settings.CONFIG_PATH.with_suffix(".tmp")
        tmp.write_text(render(state))
        tmp.replace(settings.CONFIG_PATH)
        return True
    except OSError as e:
        logger.warning("could not write mediamtx config: %s", e)
        return False


async def readers(stream: str) -> int | None:
    """How many clients are pulling the path. None if the API is unreachable.

    None and 0 are different answers and the UI says so: one means the
    server is not talking to us, the other means nobody is watching.
    """
    import httpx

    url = f"http://{settings.INTERNAL_HOST}:9997/v3/paths/get/{stream}"
    try:
        async with httpx.AsyncClient(timeout=2.0) as client:
            resp = await client.get(url)
        if resp.status_code != 200:
            return None
        data = resp.json()
    except Exception:
        return None
    value = data.get("readers")
    if isinstance(value, list):
        return len(value)
    return None
