"""Configure cameras to publish object positions, and serve what arrives.

The manual version of this is a sequence of steps where every one of them
fails silently in the same way -- the camera connects and simply never
publishes -- so the endpoints here check the preconditions up front and
name the specific thing that is wrong.
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Any
from uuid import UUID

import httpx
from fastapi import APIRouter, Depends, HTTPException, Query, Request
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from starlette.responses import FileResponse, Response, StreamingResponse

import re
import tempfile
from collections import OrderedDict, deque
from pathlib import Path

from app.connectors.verkada.client import VerkadaApiError, VerkadaClient
from app.connectors.verkada.footage import (
    CLIP_ROOT,
    FootageError,
    get_stream_key,
    grab_still_frame,
    grab_video_clip,
)
from app.crypto import decrypt_secret
from app.db import get_session
from app.models import Connection, VerkadaCamera
from app.mqtt import broker_mode, filters, history, provision, requirements
from app.mqtt.ingest import ingest


logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/mqtt", tags=["mqtt"])

# The CA the camera is told to trust; handing it the leaf instead is the
# classic "unknown ca" failure. Generated by /api/mqtt/setup.
CA_PATH = provision.CA_PATH

# Verkada rejects anything else in broker_host_port.
ALLOWED_PORTS = {"443", "123", "53"}


class MqttStatus(BaseModel):
    connected: bool
    enabled: bool
    host: str
    topic: str
    last_error: str | None
    uptime_sec: float | None
    total_messages: int
    cameras: list[str]
    track_timeout_sec: float
    last_message_age_sec: float | None
    ca_present: bool
    credentials_present: bool
    broker_username: str | None
    mode: str
    # host:port cameras should be pointed at, from the certificate.
    broker_host_port: str | None


@router.get("/status", response_model=MqttStatus)
async def status() -> MqttStatus:
    """Is the ingest loop up, and has anything ever arrived on it."""
    state = provision.state()
    return MqttStatus(
        **ingest.status(),
        ca_present=bool(state["ca_present"]),
        credentials_present=bool(state["credentials_present"]),
        broker_username=state["username"],
        broker_host_port=broker_mode.camera_target()["broker_host_port"] or None,
        mode=broker_mode.get()["mode"],
    )


class PreflightCheck(BaseModel):
    id: str
    label: str
    # ok = verified good, fail = verified bad, unknown = we could not tell
    state: str
    detail: str
    fix: str | None = None


@router.get("/preflight/{camera_id}", response_model=list[PreflightCheck])
async def preflight(
    camera_id: str,
    connection_id: UUID | None = Query(default=None),
    session: AsyncSession = Depends(get_session),
) -> list[PreflightCheck]:
    """Everything that has to be true before a camera will publish.

    Each of these has cost somebody an afternoon at least once. The
    occupancy-trends line is the worst of them: without it the camera
    connects, authenticates, and publishes nothing at all, which looks
    identical to a broken broker.
    """
    checks: list[PreflightCheck] = []

    checks.append(
        PreflightCheck(
            id="ca",
            label="Broker certificate generated",
            state="ok" if CA_PATH.is_file() else "fail",
            detail=(
                "root_ca.pem is present and will be pushed to the camera."
                if CA_PATH.is_file()
                else "No CA found at mqtt/certs/root_ca.pem."
            ),
            fix=None if CA_PATH.is_file() else "Run ./mqtt/gen-certs.sh <broker-address> on the host.",
        )
    )

    checks.append(
        PreflightCheck(
            id="ingest",
            label="Broker reachable from vFusion",
            state="ok" if ingest.connected else "fail",
            detail=(
                "Subscribed to the ingest broker."
                if ingest.connected
                else f"Not connected: {ingest.last_error or 'ingest disabled'}"
            ),
            # detail already carries the specific command when we know
            # what went wrong; a generic fix underneath it just competes.
            fix=(
                None
                if ingest.connected or ingest.last_error
                else "Start the broker: docker compose --profile mqtt up -d"
            ),
        )
    )

    cam = (
        await session.execute(
            select(VerkadaCamera).where(VerkadaCamera.camera_id == camera_id)
        )
    ).scalars().first()

    if cam is None:
        checks.append(
            PreflightCheck(
                id="camera",
                label="Camera known",
                state="unknown",
                detail="Camera is not in the local cache.",
                fix="Sync cameras on the Connections page.",
            )
        )
        return checks

    online = bool(cam.status) and cam.status.lower() != "offline"
    checks.append(
        PreflightCheck(
            id="online",
            label="Camera online",
            state="ok" if online else "fail",
            detail=f"Status is {cam.status or 'unknown'}.",
            fix=None if online else "An offline camera cannot be configured or publish.",
        )
    )

    raw = cam.raw if isinstance(cam.raw, dict) else {}
    people = raw.get("people_history_enabled")
    checks.append(
        PreflightCheck(
            id="analytics",
            label="People analytics enabled",
            state="ok" if people else ("fail" if people is False else "unknown"),
            detail=f"people_history_enabled is {people!r}.",
            fix=None if people else "Enable People History on the camera in Command.",
        )
    )

    # The occupancy-trends line. There is no API to draw one, so the most
    # this can do is tell the operator to go draw it.
    checks.append(await _occupancy_check(session, camera_id, connection_id))
    checks.append(await _existing_config_check(session, camera_id, connection_id))
    return checks


def _normalise_pem(text: str) -> str:
    """Compare certificates by content, ignoring line-ending noise."""
    return "".join(str(text or "").split())


async def _existing_config_check(
    session: AsyncSession, camera_id: str, connection_id: UUID | None
) -> PreflightCheck:
    """Whether this camera is already pointed here, with the current cert.

    Without this the page looks identical for a camera that was
    configured months ago and one that has never been touched, so the
    only way to find out is to push again — and a push rotates nothing
    but does churn the camera's connection for 5-25 seconds.

    The certificate matters as much as the address: after regenerating,
    every camera still holds the old CA and will fail the handshake
    while looking perfectly configured.
    """
    unknown = PreflightCheck(
        id="pushed",
        label="Already pointed at this broker",
        state="unknown",
        detail="Could not read the camera's current config.",
    )
    client = await _client_for(session, connection_id)
    if client is None:
        unknown.detail = "No Verkada connection is set up."
        return unknown
    try:
        config = await client.get_object_position_mqtt_config(camera_id)
    except VerkadaApiError as e:
        unknown.detail = _permission_hint(e)
        return unknown

    host_port = str(config.get("broker_host_port") or "")
    if not host_port:
        return PreflightCheck(
            id="pushed",
            label="Already pointed at this broker",
            state="fail",
            detail="Not configured yet — this camera has no broker set.",
            fix="Push the config below.",
        )

    expected = broker_mode.camera_target()["broker_host_port"]
    if expected and host_port != expected:
        return PreflightCheck(
            id="pushed",
            label="Already pointed at this broker",
            state="fail",
            detail=f"Pointed at {host_port} rather than {expected}.",
            fix="Push the config below to move it here.",
        )

    ca = broker_mode.camera_target()["broker_cert"]
    if ca and _normalise_pem(config.get("broker_cert", "")) != _normalise_pem(ca):
        return PreflightCheck(
            id="pushed",
            label="Already pointed at this broker",
            state="fail",
            detail=(
                f"Set to {host_port}, but holding a different certificate than "
                "the one generated here — the TLS handshake will fail."
            ),
            fix="Push the config below to send the current certificate.",
        )

    return PreflightCheck(
        id="pushed",
        label="Already pointed at this broker",
        state="ok",
        detail=(
            f"Configured for {host_port} as "
            f"{config.get('client_username') or 'unknown user'}, with the current "
            "certificate. No need to push again."
        ),
    )


async def _occupancy_check(
    session: AsyncSession, camera_id: str, connection_id: UUID | None
) -> PreflightCheck:
    unknown = PreflightCheck(
        id="line",
        label="Occupancy Trends line drawn",
        state="unknown",
        detail="Could not verify.",
        fix=(
            "Command → Camera → Analytics → Occupancy Trends → Edit Lines. "
            "Without a line the camera connects but never publishes."
        ),
    )
    client = await _client_for(session, connection_id)
    if client is None:
        unknown.detail = "No Verkada connection is set up."
        return unknown
    try:
        cameras = await client.list_occupancy_trend_cameras()
    except VerkadaApiError as e:
        if e.status_code == 403:
            unknown.detail = (
                "Verkada returned 403 reading occupancy trends. That can mean the "
                "key lacks the scope, but Verkada also answers unknown paths with "
                "403 — the line itself may well be fine."
            )
        else:
            unknown.detail = f"Lookup failed: {e}"
        return unknown

    hit = next(
        (c for c in cameras if isinstance(c, dict) and c.get("camera_id") == camera_id),
        None,
    )
    presets = (hit or {}).get("preset_ids") or []
    if hit and presets:
        classes = sorted(
            {
                p.get("object_class")
                for p in (hit.get("presets") or [])
                if isinstance(p, dict) and p.get("object_class")
            }
        )
        detail = f"{len(presets)} line preset(s) configured."
        if classes:
            detail += (
                f" Tracking {', '.join(classes)} — a class with no line "
                "drawn for it will not be reported."
            )
        return PreflightCheck(
            id="line", label="Occupancy Trends line drawn", state="ok", detail=detail
        )
    return PreflightCheck(
        id="line",
        label="Occupancy Trends line drawn",
        state="fail",
        detail="No line preset on this camera — it will connect but never publish.",
        fix="Command → Camera → Analytics → Occupancy Trends → Edit Lines.",
    )


async def _client_for(
    session: AsyncSession, connection_id: UUID | None
) -> VerkadaClient | None:
    q = select(Connection).where(Connection.type == "verkada")
    if connection_id:
        q = q.where(Connection.id == connection_id)
    conn = (await session.execute(q)).scalars().first()
    if conn is None:
        return None
    try:
        secret = decrypt_secret(conn.encrypted_secret)
    except Exception:
        return None
    api_key = secret.get("api_key")
    if not api_key:
        return None
    return VerkadaClient(api_key=api_key, base_url=secret.get("region") or None)


class ConfigureRequest(BaseModel):
    # No address: it comes from the configured broker, because it has to
    # match the certificate sent alongside it.
    connection_id: UUID | None = None


@router.get("/config/{camera_id}")
async def get_config(
    camera_id: str,
    connection_id: UUID | None = Query(default=None),
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    """What the camera currently thinks its broker is."""
    client = await _client_for(session, connection_id)
    if client is None:
        raise HTTPException(status_code=400, detail="no Verkada connection configured")
    try:
        return await client.get_object_position_mqtt_config(camera_id)
    except VerkadaApiError as e:
        raise HTTPException(status_code=400, detail=_permission_hint(e)) from e


@router.post("/config/{camera_id}")
async def set_config(
    camera_id: str,
    body: ConfigureRequest,
    dry_run: bool = Query(default=False, description="Show the request without sending it"),
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    """Point a camera at this broker, then read it back to prove it stuck.

    The read-back is not defensive padding. The API returns 200 and
    silently discards the config if either credential is missing, so the
    only way to know it took is to ask.
    """
    host_port = broker_mode.camera_target()["broker_host_port"]
    _, _, port = host_port.rpartition(":")
    if port not in ALLOWED_PORTS:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Broker port {port or '(none)'} is not usable — Verkada only "
                "accepts 443, 123 or 53."
            ),
        )
    # Built in: generated certificate and stored credentials. External:
    # whatever was entered, because vFusion cannot derive either.
    target = broker_mode.camera_target()
    missing = [
        name
        for name, value in (
            ("broker address", target["broker_host_port"]),
            ("username", target["client_username"]),
            ("password", target["client_password"]),
            ("broker certificate", target["broker_cert"]),
        )
        if not value
    ]
    if missing:
        raise HTTPException(
            status_code=400,
            detail=(
                "Broker setup is incomplete — missing "
                + ", ".join(missing)
                + ". Finish step 0 first."
            ),
        )
    creds = {
        "username": target["client_username"],
        "password": target["client_password"],
    }

    client = await _client_for(session, body.connection_id)
    if client is None:
        raise HTTPException(status_code=400, detail="no Verkada connection configured")

    ca = target["broker_cert"]
    preview = _request_preview(camera_id, target["broker_host_port"], creds, ca)
    if dry_run:
        return {"dry_run": True, "request": preview}

    try:
        await client.set_object_position_mqtt_config(
            camera_id=camera_id,
            broker_host_port=target["broker_host_port"],
            client_username=creds["username"],
            client_password=creds["password"],
            broker_cert=ca,
        )
    except VerkadaApiError as e:
        # Hand back the request alongside the error: "insufficient
        # permissions" on an endpoint the operator has rights to is
        # almost always a malformed request, and guessing which is
        # which without seeing it wastes an afternoon.
        raise HTTPException(
            status_code=400,
            detail={"error": _permission_hint(e), "request": preview},
        ) from e

    # Read back separately: the write is what matters, and a failure to
    # confirm it is not a failure to do it. Conflating the two reported
    # a successful push as a permissions error.
    readback: dict[str, Any] = {}
    readback_error: str | None = None
    try:
        readback = await client.get_object_position_mqtt_config(camera_id)
    except VerkadaApiError as e:
        readback_error = f"Config was sent, but reading it back failed: {e}"

    persisted = bool(readback.get("broker_host_port")) and bool(
        readback.get("client_username")
    )
    return {
        "persisted": persisted,
        "config": readback,
        "request": preview,
        "readback_error": readback_error,
        "note": (
            "Camera reconnects within ~5–25s of a config change."
            if persisted
            else readback_error
            or "Verkada accepted the call but stored nothing — re-send with both credentials."
        ),
    }


def _request_preview(
    camera_id: str, broker_host_port: str, creds: dict[str, str], ca: str
) -> dict[str, Any]:
    """Exactly what we send Verkada, with the secrets rendered inert.

    A 403 from an endpoint you believe you have rights to is usually the
    request being wrong rather than the key, and there is no way to tell
    those apart without seeing what actually went out. The API key never
    appears -- not even partially -- because this is meant to be
    screenshot-able.
    """
    ca_lines = ca.strip().splitlines()
    return {
        "method": "POST",
        "url": "https://api.verkada.com/cameras/v1/analytics/object_position_mqtt",
        "headers": {
            "x-verkada-auth": "<token minted from the connection's API key>",
            "content-type": "application/json",
        },
        "body": {
            "camera_id": camera_id,
            "broker_host_port": broker_host_port,
            "client_username": creds["username"],
            "client_password": f"<{len(creds['password'])} chars>",
            "broker_cert": (
                f"{ca_lines[0] if ca_lines else ''} … "
                f"{len(ca_lines)} lines, {len(ca)} chars"
            ),
        },
        "notes": [
            "Auth is a short-lived token from POST /token, not the API key itself.",
            "Both credentials must be present or Verkada 200s and stores nothing.",
            "broker_cert must be the CA, not the server leaf.",
        ],
    }


def _permission_hint(e: VerkadaApiError) -> str:
    if e.status_code == 403:
        # Verkada returns this for an unknown path as well as a genuine
        # scope problem, so do not assert which one it is.
        return (
            "Verkada returned 403. That usually means the API key lacks read/write "
            "access to Cameras, but Verkada also answers unknown paths with 403, "
            "so check the request above before changing key permissions."
        )
    if e.status_code == 401:
        return "Verkada rejected the API key (401)."
    return str(e)


class SetupRequest(BaseModel):
    broker_host: str
    username: str = "vfusion"
    # Omit to have one generated -- it is only ever typed by a camera.
    password: str | None = None
    # Existing credentials are reused by default. Changing them requires
    # restarting mosquitto, which vFusion cannot do, so it should be a
    # thing you asked for rather than a side effect of regenerating certs.
    rotate_password: bool = False


@router.post("/setup")
async def setup(body: SetupRequest) -> dict[str, Any]:
    """Generate the broker's certificate and credentials.

    Everything here used to be a shell script run on the docker host. The
    address matters more than it looks: it is baked into the certificate's
    SAN, so changing it later invalidates every camera already pointed
    here and means re-pushing all of them.
    """
    host = body.broker_host.strip()
    if ":" in host and not host.startswith("["):
        # Easy mistake, since the camera field does want host:port.
        raise HTTPException(
            status_code=400,
            detail="Enter the host or IP only — the port is always 443 here.",
        )
    if not host:
        raise HTTPException(status_code=400, detail="broker_host is required")

    existing = provision.load_credentials()
    reuse = existing is not None and not body.rotate_password and body.password is None
    password = (
        existing["password"] if reuse and existing else (body.password or provision.generate_password())
    )
    username = existing["username"] if reuse and existing else body.username
    try:
        info = provision.generate_certs(host)
        if not reuse:
            # Only touch the password file when the password actually
            # changes: mosquitto reads it once at startup, so rewriting it
            # under a running broker locks out the very credentials this
            # process is about to use.
            provision.write_password_file(username, password)
            provision.save_credentials(username, password)
    except OSError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Could not write to {provision.MQTT_DIR}: {e}",
        ) from e

    await ingest.restart()
    restart_needed = ["mqtt-tls"] + ([] if reuse else ["mqtt-broker"])
    return {
        "broker_host_port": f"{host}:443",
        "username": username,
        "password_rotated": not reuse,
        "san": info["san"],
        "expires": info["expires"],
        # Deliberately no password here. It is stored encrypted and used
        # directly when configuring a camera, so there is nothing for the
        # operator to write down and nothing to lose by closing the tab.
        "next_steps": [
            "Start the broker:  docker compose --profile mqtt up -d",
            "Already running?  docker compose restart " + " ".join(restart_needed)
            + ("  (mosquitto only reads its password file at startup)" if not reuse
               else "  (nginx only reads certificates at startup)"),
        ],
    }


@router.delete("/config/{camera_id}")
async def clear_config(
    camera_id: str,
    connection_id: UUID | None = Query(default=None),
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    """Unpoint a camera from its broker.

    Also the documented way to force a reconnect: the camera only acts on
    a config *change*, so re-pushing identical settings may do nothing
    while clear-then-set reliably brings it back within ~5-25s.
    """
    client = await _client_for(session, connection_id)
    if client is None:
        raise HTTPException(status_code=400, detail="no Verkada connection configured")
    try:
        await client.set_object_position_mqtt_config(
            camera_id=camera_id,
            broker_host_port="",
            client_username="",
            client_password="",
            broker_cert="",
        )
    except VerkadaApiError as e:
        raise HTTPException(status_code=400, detail=_permission_hint(e)) from e
    return {"cleared": True}


@router.post("/reset")
async def reset() -> dict[str, Any]:
    """Delete the generated certificate, password file and credentials.

    For starting over after the broker address changes -- the address is
    baked into the certificate SAN, so a move invalidates everything and
    every camera has to be re-pushed anyway.
    """
    removed = provision.clear()
    await ingest.restart()
    return {
        "removed": removed,
        "note": (
            "Cameras still point here until re-pushed. "
            "Restart mqtt-broker and mqtt-tls after generating again."
        ),
    }


# Segment names in the upstream playlist. Anchored so the proxy can only
# ever be pointed at Verkada's own stream files, never an arbitrary URL.
_SEGMENT_RE = re.compile(r"^[A-Za-z0-9_.-]+\.(m4s|mp4|ts)$")

STREAM_BASE = "/stream/cameras/v1/footage/stream"

# Upstream publishes a two-segment window -- eight seconds against a
# four-second target duration. Apple's spec says a client should not start
# playback until a live playlist holds three target durations, so Safari
# fetches the init segment and then reloads the playlist forever without
# ever requesting media. hls.js ignores the rule and plays, which is why
# this looked like a Safari-only codec problem.
#
# So remember the segments we have already seen and republish a longer
# window. The names stay valid upstream for a while, and anything we
# served recently is still in the segment cache.
_WINDOW: "dict[str, deque]" = {}
_WINDOW_SEGMENTS = 6


async def _connection_for(
    session: AsyncSession, connection_id: UUID | None
) -> Connection:
    q = select(Connection).where(Connection.type == "verkada")
    if connection_id:
        q = q.where(Connection.id == connection_id)
    conn = (await session.execute(q)).scalars().first()
    if conn is None:
        raise HTTPException(status_code=400, detail="no Verkada connection configured")
    return conn


async def _stream_context(
    session: AsyncSession, connection_id: UUID | None
) -> tuple[str, str, str]:
    """(base_url, org_id, jwt) for the live HLS stream."""
    q = select(Connection).where(Connection.type == "verkada")
    if connection_id:
        q = q.where(Connection.id == connection_id)
    conn = (await session.execute(q)).scalars().first()
    if conn is None:
        raise HTTPException(status_code=400, detail="no Verkada connection configured")
    try:
        secret = decrypt_secret(conn.encrypted_secret)
    except Exception as e:
        raise HTTPException(status_code=400, detail="could not decrypt connection") from e
    api_key = secret.get("api_key")
    org_id = conn.external_id
    if not api_key or not org_id:
        raise HTTPException(
            status_code=400, detail="connection is missing an API key or org id"
        )
    base = (secret.get("region") or "https://api.verkada.com").rstrip("/")
    try:
        jwt = await get_stream_key(api_key, org_id, base_url=base)
    except FootageError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    return base, org_id, jwt


def _stream_query(org_id: str, camera_id: str, jwt: str) -> dict[str, str]:
    """Query for the live HLS stream.

    low_res, not high_res, and the reason is the whole feature: Verkada
    serves high_res as HEVC and low_res as H.264. No transcode flag
    changes that -- transcode=true still returns hevc at high_res. HEVC
    is why nothing rendered: Chrome downloaded segments and decoded
    nothing, and the codebase's existing consumers all run the stream
    through ffmpeg, which decodes it happily and hid the problem.

    low_res also happens to publish three segments rather than two,
    which satisfies the three-target-durations rule Safari enforces
    before it will start a live stream.

    Resolution costs nothing here: the boxes are normalised coordinates
    and scale to whatever size the video renders at.
    """
    return {
        "org_id": org_id,
        "camera_id": camera_id,
        "resolution": "low_res",
        "type": "stream",
        "codec": "h264",
        "transcode": "false",
        "start_time": "0",
        "end_time": "0",
        "jwt": jwt,
    }


@router.get("/stream/{camera_id}/index.m3u8")
async def stream_playlist(
    camera_id: str,
    connection_id: UUID | None = Query(default=None),
    session: AsyncSession = Depends(get_session),
) -> Response:
    """Live HLS playlist with the credentials stripped out.

    Every segment URI upstream carries a signed JWT, so handing the
    playlist straight to a browser would publish a working stream
    credential into the DOM and the network log. This rewrites each URI
    to a path on this server and keeps the token here; the proxy rebuilds
    the real query when fetching a segment.
    """
    base, org_id, jwt = await _stream_context(session, connection_id)
    async with httpx.AsyncClient(timeout=20.0) as client:
        res = await client.get(
            f"{base}{STREAM_BASE}/stream.m3u8",
            params=_stream_query(org_id, camera_id, jwt),
        )
    if res.status_code != 200:
        raise HTTPException(
            status_code=502, detail=f"stream playlist failed: HTTP {res.status_code}"
        )

    header: list[str] = []
    fresh: list[tuple[str, list[str]]] = []
    pending: list[str] = []
    upstream_seq = 0
    for line in res.text.splitlines():
        if line.startswith("#EXT-X-MAP:"):
            m = re.search(r'URI="([^"?]+)', line)
            if m:
                header.append(f'#EXT-X-MAP:URI="seg/{m.group(1)}"')
            continue
        if line.startswith("#EXT-X-MEDIA-SEQUENCE:"):
            try:
                upstream_seq = int(line.split(":", 1)[1])
            except ValueError:
                upstream_seq = 0
            continue
        if line.startswith("#EXTINF") or line.startswith("#EXT-X-PROGRAM-DATE-TIME"):
            pending.append(line)
            continue
        if line.startswith("#"):
            header.append(line)
            continue
        if line:
            fresh.append((line.split("?", 1)[0], pending))
            pending = []

    window = _WINDOW.setdefault(camera_id, deque(maxlen=_WINDOW_SEGMENTS))
    known = {name for name, _ in window}
    for name, tags in fresh:
        if name not in known:
            window.append((name, tags))

    names = [name for name, _ in window]
    # MEDIA-SEQUENCE must number the first segment we publish, which is
    # older than the first one upstream is currently advertising.
    older = 0
    if fresh:
        first_upstream = fresh[0][0]
        older = names.index(first_upstream) if first_upstream in names else 0
    body = header + [f"#EXT-X-MEDIA-SEQUENCE:{max(0, upstream_seq - older)}"]
    for name, tags in window:
        body.extend(tags)
        body.append(f"seg/{name}")

    return Response(
        content="\n".join(body) + "\n",
        media_type="application/vnd.apple.mpegurl",
        headers={"Cache-Control": "no-store"},
    )


# Recently fetched segments, so a range probe followed by the real read
# does not pull the same ~700 KB twice. Small on purpose: this is a live
# stream, and anything more than a few seconds back is never asked for.
_SEG_CACHE: "OrderedDict[str, bytes]" = OrderedDict()
_SEG_CACHE_MAX = 8


def _parse_range(header: str, size: int) -> tuple[int, int] | None:
    """Resolve a single-range header to inclusive (start, end) offsets."""
    if not header.startswith("bytes="):
        return None
    spec = header[6:].split(",", 1)[0].strip()
    try:
        if spec.startswith("-"):
            length = int(spec[1:])
            if length <= 0:
                return None
            return max(0, size - length), size - 1
        first, _, last = spec.partition("-")
        begin = int(first)
        finish = int(last) if last else size - 1
    except ValueError:
        return None
    finish = min(finish, size - 1)
    if begin > finish or begin >= size:
        return None
    return begin, finish


@router.get("/stream/{camera_id}/seg/{name}")
async def stream_segment(
    camera_id: str,
    name: str,
    request: Request,
    connection_id: UUID | None = Query(default=None),
    session: AsyncSession = Depends(get_session),
) -> Response:
    """Proxy one media segment, re-attaching the credentials server-side.

    Ranges are satisfied here rather than upstream, because Verkada
    ignores the header and answers every request with the whole object.
    Forwarding it and passing the 200 back meant advertising range
    support we did not provide -- which is worse than not advertising it:
    hls.js does not care, but Safari's native player probes with a Range,
    expects a 206, and on getting a 200 fetches the init segment and then
    silently stops asking for media.
    """
    if not _SEGMENT_RE.match(name):
        raise HTTPException(status_code=400, detail="bad segment name")

    key = f"{camera_id}/{name}"
    cached = _SEG_CACHE.get(key)
    if cached is None:
        base, org_id, jwt = await _stream_context(session, connection_id)
        async with httpx.AsyncClient(timeout=30.0) as client:
            res = await client.get(
                f"{base}{STREAM_BASE}/{name}",
                params=_stream_query(org_id, camera_id, jwt),
            )
        if res.status_code != 200:
            raise HTTPException(
                status_code=502, detail=f"segment failed: HTTP {res.status_code}"
            )
        cached = res.content
        _SEG_CACHE[key] = cached
        while len(_SEG_CACHE) > _SEG_CACHE_MAX:
            _SEG_CACHE.popitem(last=False)
    else:
        _SEG_CACHE.move_to_end(key)

    size = len(cached)
    headers = {
        "Cache-Control": "no-store",
        "Accept-Ranges": "bytes",
    }
    rng = request.headers.get("range")
    if rng:
        span = _parse_range(rng, size)
        if span is None:
            return Response(
                status_code=416,
                headers={**headers, "Content-Range": f"bytes */{size}"},
            )
        begin, finish = span
        body = cached[begin : finish + 1]
        headers["Content-Range"] = f"bytes {begin}-{finish}/{size}"
        return Response(
            content=body,
            status_code=206,
            media_type="video/mp4",
            headers=headers,
        )

    return Response(
        content=cached,
        media_type="video/mp4",
        headers=headers,
    )


class ClipRequest(BaseModel):
    camera_id: str
    # Epoch seconds, from a recorded track's started_at.
    start_epoch: int
    duration_sec: float = 10.0
    connection_id: UUID | None = None


@router.post("/clip")
async def make_clip(
    body: ClipRequest,
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    """Cut the footage a recorded track happened in.

    Same route the flow actions take: ffmpeg pulls the window out of the
    HLS stream and writes H.264 to CLIP_ROOT, which plays in any browser
    without a JS player. Clips are named from what they contain, so
    replaying the same track twice reuses the file instead of paying for
    another encode.
    """
    conn = await _connection_for(session, body.connection_id)
    secret = decrypt_secret(conn.encrypted_secret)
    org_id = conn.external_id
    if not secret.get("api_key") or not org_id:
        raise HTTPException(status_code=400, detail="connection is missing an API key or org id")

    duration = max(1.0, min(float(body.duration_sec), 120.0))
    # A little either side: tracks start when the camera first reports a
    # box, which is usually already mid-approach.
    pad = 2.0
    start = int(body.start_epoch - pad)
    total = duration + (pad * 2)

    clip_id = f"{body.camera_id}_{start}_{int(total)}"
    out_path = CLIP_ROOT / f"{clip_id}.mp4"
    if not out_path.exists():
        try:
            await grab_video_clip(
                api_key=secret["api_key"],
                org_id=org_id,
                camera_id=body.camera_id,
                start_epoch=start,
                duration_sec=total,
                out_path=out_path,
                base_url=(secret.get("region") or "https://api.verkada.com").rstrip("/"),
            )
        except FootageError as e:
            raise HTTPException(
                status_code=502,
                detail=(
                    f"Could not cut the clip: {e}. Verkada backfills footage for "
                    "a minute or so after an event, so very recent tracks may "
                    "not be retrievable yet."
                ),
            ) from e

    return {
        "clip_id": clip_id,
        "url": f"/api/mqtt/clip/{clip_id}.mp4",
        "duration_sec": total,
        # The client needs this to line the two panels up: video time
        # pad_sec corresponds to track time zero.
        "pad_sec": pad,
    }


@router.get("/clip/{clip_name}")
async def get_clip(clip_name: str) -> FileResponse:
    """Serve a cut clip. FileResponse handles Range, which video needs."""
    if not re.fullmatch(r"[A-Za-z0-9_.-]+\.mp4", clip_name):
        raise HTTPException(status_code=400, detail="bad clip name")
    path = CLIP_ROOT / clip_name
    if not path.is_file():
        raise HTTPException(status_code=404, detail="clip not found")
    return FileResponse(path, media_type="video/mp4")


class FiltersRequest(BaseModel):
    # Fraction of the frame, both of them.
    min_area: float
    min_movement: float


class BrokerModeRequest(BaseModel):
    mode: str
    host: str = ""
    port: int = 443
    username: str = ""
    # Blank means "leave as is" — the UI never receives these back.
    password: str = ""
    broker_cert: str = ""


@router.get("/broker-requirements")
async def broker_requirements() -> dict[str, Any]:
    """What a broker must do before a camera will publish to it.

    None of this is discoverable from the API — a camera accepts a
    configuration it cannot use and then reports nothing — so it is
    surfaced next to the form where someone is entering their own
    broker details.
    """
    return requirements.describe()


@router.get("/broker-mode")
async def get_broker_mode() -> dict[str, Any]:
    return broker_mode.public()


@router.put("/broker-mode")
async def set_broker_mode(body: BrokerModeRequest) -> dict[str, Any]:
    if body.mode not in ("builtin", "external"):
        raise HTTPException(status_code=400, detail="mode must be builtin or external")
    if body.mode == "external":
        if not body.host.strip():
            raise HTTPException(status_code=400, detail="an external broker needs a host")
        if body.port not in (443, 123, 53):
            raise HTTPException(
                status_code=400,
                detail="Verkada only accepts port 443, 123 or 53 in broker_host_port",
            )
        existing = broker_mode.get()
        if not (body.broker_cert.strip() or existing.get("broker_cert")):
            raise HTTPException(
                status_code=400,
                detail=(
                    "an external broker needs its CA certificate — the camera "
                    "validates against it and rejects anything else"
                ),
            )
    return await broker_mode.put(body.model_dump())


@router.get("/filters")
async def get_filters() -> dict[str, Any]:
    """Thresholds a detection must clear before it is reported."""
    return filters.describe()


@router.put("/filters")
async def set_filters(body: FiltersRequest) -> dict[str, Any]:
    await filters.put(body.min_area, body.min_movement)
    return filters.describe()


@router.get("/filters/preview")
async def preview_filters(
    min_area: float = Query(default=0.01),
    min_movement: float = Query(default=0.0),
    camera_id: str | None = Query(default=None),
) -> dict[str, Any]:
    """What these thresholds would have done to the tracks on record.

    Chosen thresholds are guesses until they are checked against real
    detections, and the history already holds several hundred of them —
    so the slider can say "keeps 6, drops 221" instead of leaving
    someone to find out over the following week.
    """
    tracks = history.read(camera_id=camera_id, limit=2000)
    kept: list[dict[str, Any]] = []
    dropped: list[dict[str, Any]] = []
    for t in tracks:
        area, travelled = history.measure(t)
        row = {**t, "area": round(area, 4), "travelled": round(travelled, 4)}
        if area >= min_area and (min_movement <= 0 or travelled >= min_movement):
            kept.append(row)
        else:
            dropped.append(row)

    by_type: dict[str, int] = {}
    for t in kept:
        by_type[t.get("type", "unknown")] = by_type.get(t.get("type", "unknown"), 0) + 1

    # The survivors closest to being cut. A count of what a threshold
    # removes says nothing about whether it is about to remove something
    # real — these are the rows to look at for that.
    def margin(row: dict[str, Any]) -> float:
        m = row["area"] - min_area
        if min_movement > 0:
            m = min(m, row["travelled"] - min_movement)
        return m

    marginal = sorted(kept, key=margin)[:8]

    return {
        "considered": len(tracks),
        "kept": len(kept),
        "dropped": len(dropped),
        "kept_by_type": by_type,
        # Capped: this is for eyeballing, and the whole set is on record.
        "would_drop": dropped[:60],
        "closest_kept": marginal,
    }


class PurgeRequest(BaseModel):
    min_area: float
    min_movement: float


@router.post("/filters/purge")
async def purge_history(body: PurgeRequest) -> dict[str, Any]:
    """Delete recorded tracks that fail these thresholds.

    Separate from saving the thresholds: applying a filter going forward
    and rewriting what is already on record are different decisions, and
    the second one cannot be undone.
    """
    result = await asyncio.to_thread(
        history.prune_below, body.min_area, body.min_movement
    )
    return result


@router.get("/history")
async def track_history(
    camera_id: str | None = Query(default=None),
    object_type: str | None = Query(default=None),
    limit: int = Query(default=200, le=2000),
) -> dict[str, Any]:
    """Completed tracks, most recent first, with a summary.

    One row per object rather than per message: the live view already
    shows the messages, and what you want hours later is "what came
    through, when, and for how long".
    """
    return {
        "tracks": history.read(camera_id=camera_id, limit=limit, object_type=object_type),
        "summary": history.summarize(camera_id=camera_id),
    }


@router.get("/frame/{camera_id}")
async def frame(
    camera_id: str,
    epoch: int | None = Query(default=None, description="Still from this moment instead of now"),
    connection_id: UUID | None = Query(default=None),
    session: AsyncSession = Depends(get_session),
) -> Response:
    """A single live frame, pulled from the HLS stream with ffmpeg.

    The thumbnail endpoint is cheaper but lags — it serves the camera's
    last stored still, which can be a minute old and makes the boxes look
    wrong against it. This decodes one frame from the live stream, which
    is what the rest of the codebase already does for the same reason.

    Proxied as bytes so the signed stream URL never reaches the browser.
    """
    base, org_id, jwt = await _stream_context(session, connection_id)
    async with httpx.AsyncClient(timeout=20.0) as client:
        res = await client.get(
            f"{base}{STREAM_BASE}/stream.m3u8",
            params=_stream_query(org_id, camera_id, jwt),
        )
    if res.status_code != 200:
        raise HTTPException(
            status_code=502, detail=f"stream playlist failed: HTTP {res.status_code}"
        )

    header: list[str] = []
    fresh: list[tuple[str, list[str]]] = []
    pending: list[str] = []
    upstream_seq = 0
    for line in res.text.splitlines():
        if line.startswith("#EXT-X-MAP:"):
            m = re.search(r'URI="([^"?]+)', line)
            if m:
                header.append(f'#EXT-X-MAP:URI="seg/{m.group(1)}"')
            continue
        if line.startswith("#EXT-X-MEDIA-SEQUENCE:"):
            try:
                upstream_seq = int(line.split(":", 1)[1])
            except ValueError:
                upstream_seq = 0
            continue
        if line.startswith("#EXTINF") or line.startswith("#EXT-X-PROGRAM-DATE-TIME"):
            pending.append(line)
            continue
        if line.startswith("#"):
            header.append(line)
            continue
        if line:
            fresh.append((line.split("?", 1)[0], pending))
            pending = []

    window = _WINDOW.setdefault(camera_id, deque(maxlen=_WINDOW_SEGMENTS))
    known = {name for name, _ in window}
    for name, tags in fresh:
        if name not in known:
            window.append((name, tags))

    names = [name for name, _ in window]
    # MEDIA-SEQUENCE must number the first segment we publish, which is
    # older than the first one upstream is currently advertising.
    older = 0
    if fresh:
        first_upstream = fresh[0][0]
        older = names.index(first_upstream) if first_upstream in names else 0
    body = header + [f"#EXT-X-MEDIA-SEQUENCE:{max(0, upstream_seq - older)}"]
    for name, tags in window:
        body.extend(tags)
        body.append(f"seg/{name}")

    return Response(
        content="\n".join(body) + "\n",
        media_type="application/vnd.apple.mpegurl",
        headers={"Cache-Control": "no-store"},
    )


# Recently fetched segments, so a range probe followed by the real read
# does not pull the same ~700 KB twice. Small on purpose: this is a live
# stream, and anything more than a few seconds back is never asked for.
_SEG_CACHE: "OrderedDict[str, bytes]" = OrderedDict()
_SEG_CACHE_MAX = 8


def _parse_range(header: str, size: int) -> tuple[int, int] | None:
    """Resolve a single-range header to inclusive (start, end) offsets."""
    if not header.startswith("bytes="):
        return None
    spec = header[6:].split(",", 1)[0].strip()
    try:
        if spec.startswith("-"):
            length = int(spec[1:])
            if length <= 0:
                return None
            return max(0, size - length), size - 1
        first, _, last = spec.partition("-")
        begin = int(first)
        finish = int(last) if last else size - 1
    except ValueError:
        return None
    finish = min(finish, size - 1)
    if begin > finish or begin >= size:
        return None
    return begin, finish


@router.get("/stream/{camera_id}/seg/{name}")
async def stream_segment(
    camera_id: str,
    name: str,
    request: Request,
    connection_id: UUID | None = Query(default=None),
    session: AsyncSession = Depends(get_session),
) -> Response:
    """Proxy one media segment, re-attaching the credentials server-side.

    Ranges are satisfied here rather than upstream, because Verkada
    ignores the header and answers every request with the whole object.
    Forwarding it and passing the 200 back meant advertising range
    support we did not provide -- which is worse than not advertising it:
    hls.js does not care, but Safari's native player probes with a Range,
    expects a 206, and on getting a 200 fetches the init segment and then
    silently stops asking for media.
    """
    if not _SEGMENT_RE.match(name):
        raise HTTPException(status_code=400, detail="bad segment name")

    key = f"{camera_id}/{name}"
    cached = _SEG_CACHE.get(key)
    if cached is None:
        base, org_id, jwt = await _stream_context(session, connection_id)
        async with httpx.AsyncClient(timeout=30.0) as client:
            res = await client.get(
                f"{base}{STREAM_BASE}/{name}",
                params=_stream_query(org_id, camera_id, jwt),
            )
        if res.status_code != 200:
            raise HTTPException(
                status_code=502, detail=f"segment failed: HTTP {res.status_code}"
            )
        cached = res.content
        _SEG_CACHE[key] = cached
        while len(_SEG_CACHE) > _SEG_CACHE_MAX:
            _SEG_CACHE.popitem(last=False)
    else:
        _SEG_CACHE.move_to_end(key)

    size = len(cached)
    headers = {
        "Cache-Control": "no-store",
        "Accept-Ranges": "bytes",
    }
    rng = request.headers.get("range")
    if rng:
        span = _parse_range(rng, size)
        if span is None:
            return Response(
                status_code=416,
                headers={**headers, "Content-Range": f"bytes */{size}"},
            )
        begin, finish = span
        body = cached[begin : finish + 1]
        headers["Content-Range"] = f"bytes {begin}-{finish}/{size}"
        return Response(
            content=body,
            status_code=206,
            media_type="video/mp4",
            headers=headers,
        )

    return Response(
        content=cached,
        media_type="video/mp4",
        headers=headers,
    )


class ClipRequest(BaseModel):
    camera_id: str
    # Epoch seconds, from a recorded track's started_at.
    start_epoch: int
    duration_sec: float = 10.0
    connection_id: UUID | None = None


@router.post("/clip")
async def make_clip(
    body: ClipRequest,
    session: AsyncSession = Depends(get_session),
) -> dict[str, Any]:
    """Cut the footage a recorded track happened in.

    Same route the flow actions take: ffmpeg pulls the window out of the
    HLS stream and writes H.264 to CLIP_ROOT, which plays in any browser
    without a JS player. Clips are named from what they contain, so
    replaying the same track twice reuses the file instead of paying for
    another encode.
    """
    conn = await _connection_for(session, body.connection_id)
    secret = decrypt_secret(conn.encrypted_secret)
    org_id = conn.external_id
    if not secret.get("api_key") or not org_id:
        raise HTTPException(status_code=400, detail="connection is missing an API key or org id")

    duration = max(1.0, min(float(body.duration_sec), 120.0))
    # A little either side: tracks start when the camera first reports a
    # box, which is usually already mid-approach.
    pad = 2.0
    start = int(body.start_epoch - pad)
    total = duration + (pad * 2)

    clip_id = f"{body.camera_id}_{start}_{int(total)}"
    out_path = CLIP_ROOT / f"{clip_id}.mp4"
    if not out_path.exists():
        try:
            await grab_video_clip(
                api_key=secret["api_key"],
                org_id=org_id,
                camera_id=body.camera_id,
                start_epoch=start,
                duration_sec=total,
                out_path=out_path,
                base_url=(secret.get("region") or "https://api.verkada.com").rstrip("/"),
            )
        except FootageError as e:
            raise HTTPException(
                status_code=502,
                detail=(
                    f"Could not cut the clip: {e}. Verkada backfills footage for "
                    "a minute or so after an event, so very recent tracks may "
                    "not be retrievable yet."
                ),
            ) from e

    return {
        "clip_id": clip_id,
        "url": f"/api/mqtt/clip/{clip_id}.mp4",
        "duration_sec": total,
        # The client needs this to line the two panels up: video time
        # pad_sec corresponds to track time zero.
        "pad_sec": pad,
    }


@router.get("/clip/{clip_name}")
async def get_clip(clip_name: str) -> FileResponse:
    """Serve a cut clip. FileResponse handles Range, which video needs."""
    if not re.fullmatch(r"[A-Za-z0-9_.-]+\.mp4", clip_name):
        raise HTTPException(status_code=400, detail="bad clip name")
    path = CLIP_ROOT / clip_name
    if not path.is_file():
        raise HTTPException(status_code=404, detail="clip not found")
    return FileResponse(path, media_type="video/mp4")


class FiltersRequest(BaseModel):
    # Fraction of the frame, both of them.
    min_area: float
    min_movement: float


class BrokerModeRequest(BaseModel):
    mode: str
    host: str = ""
    port: int = 443
    username: str = ""
    # Blank means "leave as is" — the UI never receives these back.
    password: str = ""
    broker_cert: str = ""


@router.get("/broker-requirements")
async def broker_requirements() -> dict[str, Any]:
    """What a broker must do before a camera will publish to it.

    None of this is discoverable from the API — a camera accepts a
    configuration it cannot use and then reports nothing — so it is
    surfaced next to the form where someone is entering their own
    broker details.
    """
    return requirements.describe()


@router.get("/broker-mode")
async def get_broker_mode() -> dict[str, Any]:
    return broker_mode.public()


@router.put("/broker-mode")
async def set_broker_mode(body: BrokerModeRequest) -> dict[str, Any]:
    if body.mode not in ("builtin", "external"):
        raise HTTPException(status_code=400, detail="mode must be builtin or external")
    if body.mode == "external":
        if not body.host.strip():
            raise HTTPException(status_code=400, detail="an external broker needs a host")
        if body.port not in (443, 123, 53):
            raise HTTPException(
                status_code=400,
                detail="Verkada only accepts port 443, 123 or 53 in broker_host_port",
            )
        existing = broker_mode.get()
        if not (body.broker_cert.strip() or existing.get("broker_cert")):
            raise HTTPException(
                status_code=400,
                detail=(
                    "an external broker needs its CA certificate — the camera "
                    "validates against it and rejects anything else"
                ),
            )
    return await broker_mode.put(body.model_dump())


@router.get("/filters")
async def get_filters() -> dict[str, Any]:
    """Thresholds a detection must clear before it is reported."""
    return filters.describe()


@router.put("/filters")
async def set_filters(body: FiltersRequest) -> dict[str, Any]:
    await filters.put(body.min_area, body.min_movement)
    return filters.describe()


@router.get("/filters/preview")
async def preview_filters(
    min_area: float = Query(default=0.01),
    min_movement: float = Query(default=0.0),
    camera_id: str | None = Query(default=None),
) -> dict[str, Any]:
    """What these thresholds would have done to the tracks on record.

    Chosen thresholds are guesses until they are checked against real
    detections, and the history already holds several hundred of them —
    so the slider can say "keeps 6, drops 221" instead of leaving
    someone to find out over the following week.
    """
    tracks = history.read(camera_id=camera_id, limit=2000)
    kept: list[dict[str, Any]] = []
    dropped: list[dict[str, Any]] = []
    for t in tracks:
        area, travelled = history.measure(t)
        row = {**t, "area": round(area, 4), "travelled": round(travelled, 4)}
        if area >= min_area and (min_movement <= 0 or travelled >= min_movement):
            kept.append(row)
        else:
            dropped.append(row)

    by_type: dict[str, int] = {}
    for t in kept:
        by_type[t.get("type", "unknown")] = by_type.get(t.get("type", "unknown"), 0) + 1

    # The survivors closest to being cut. A count of what a threshold
    # removes says nothing about whether it is about to remove something
    # real — these are the rows to look at for that.
    def margin(row: dict[str, Any]) -> float:
        m = row["area"] - min_area
        if min_movement > 0:
            m = min(m, row["travelled"] - min_movement)
        return m

    marginal = sorted(kept, key=margin)[:8]

    return {
        "considered": len(tracks),
        "kept": len(kept),
        "dropped": len(dropped),
        "kept_by_type": by_type,
        # Capped: this is for eyeballing, and the whole set is on record.
        "would_drop": dropped[:60],
        "closest_kept": marginal,
    }


class PurgeRequest(BaseModel):
    min_area: float
    min_movement: float


@router.post("/filters/purge")
async def purge_history(body: PurgeRequest) -> dict[str, Any]:
    """Delete recorded tracks that fail these thresholds.

    Separate from saving the thresholds: applying a filter going forward
    and rewriting what is already on record are different decisions, and
    the second one cannot be undone.
    """
    result = await asyncio.to_thread(
        history.prune_below, body.min_area, body.min_movement
    )
    return result


@router.get("/history")
async def track_history(
    camera_id: str | None = Query(default=None),
    object_type: str | None = Query(default=None),
    limit: int = Query(default=200, le=2000),
) -> dict[str, Any]:
    """Completed tracks, most recent first, with a summary.

    One row per object rather than per message: the live view already
    shows the messages, and what you want hours later is "what came
    through, when, and for how long".
    """
    return {
        "tracks": history.read(camera_id=camera_id, limit=limit, object_type=object_type),
        "summary": history.summarize(camera_id=camera_id),
    }


@router.get("/live")
async def live(camera_id: str | None = Query(default=None)) -> StreamingResponse:
    """Server-sent stream of current boxes, pushed as messages arrive.

    Event-driven rather than polled: a fixed tick would add up to its own
    interval of latency to every object, and the point of this stream is
    to show the camera's view of the world as it happens. The one-second
    wakeup only exists so tracks visibly expire when nothing is moving.
    """

    async def gen():
        yield "retry: 2000\n\n"
        while True:
            try:
                await ingest.wait_for_change(timeout=1.0)
                payload = {
                    "cameras": ingest.snapshot(camera_id),
                    "connected": ingest.connected,
                }
                yield f"data: {json.dumps(payload)}\n\n"
            except asyncio.CancelledError:
                raise
            except Exception as e:  # never kill the stream over one frame
                logger.debug("live stream frame failed: %s", e)
                await asyncio.sleep(1.0)

    return StreamingResponse(
        gen(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )
